Command line interface realization
KruchDmitriy/software-design pull request #1
Opened 2017-03-04 10:23 UTC by KruchDmitriy

2017-03-07 18:15 UTC, KruchDmitriy commented
@yurii-litvinov

2017-03-11 15:20 UTC, yurii-litvinov requested changes
Архитектура такая, какая и ожидалась, всё работает как надо, но замечания по коду всё-таки поправьте, пожалуйста.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/Cat.java
> +package commands;
В Java традиционно принята схема именования пакетов с доменным именем организации: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/Cat.java
> +    private final String[] filenames;
Лучше fileNames --- camelCase и всё такое.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/Cat.java
> +     * @param env - environment
Дефис лучше не ставить, потому что JavaDoc сам его сгенерит. Причём, он недостаточно умный, чтобы его не генерить, если дефис уже есть, так что будет некрасиво.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/Cat.java
> +     * @param inputStream
Пустые тэги тоже не нужны, лучше всё-таки написать комментарий.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/Command.java
> +    public Command(final String[] args) {}
А зачем он? Если бы его не было, Command можно было бы сделать интерфейсом.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/Command.java
> +    public abstract InputStream run(Environment env,
Для всех public-методов нужны комментарии

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/CommandException.java
> +public class CommandException extends Exception {
И для исключений тоже :)

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/CommandFactory.java
> +public final class CommandFactory {
Нужны комментарии, здесь и классам ниже.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/commands/ExternalCommand.java
> +     * @param env
Тут и ниже тоже --- пустые тэги не нужны. Лучше либо вообще @param не писать, либо написать комментарий ко всем параметрам.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/core/InterpretException.java
> +package core;
А вообще, я думаю, исключения имеет смысл сложить в отдельный пакет, чтобы они не мешались с "основными" классами.

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/core/Interpretator.java
> +public final class Interpretator {
"Interpreter" более по-английски

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/main/java/core/Interpretator.java
> +    public static List<Command> perform(final List<String> tokens)
Название как-то не соответствует содержанию, мне кажется

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/test/java/CommandsTest.java
> +            assertTrue(false);
`fail()` здесь было бы лучше

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/test/java/CommandsTest.java
> +        }
Лучше этот тест разбить на несколько тестов (тесты ведь должны быть независимыми и проверять только один конкретный тестовый сценарий) и убрать все try-catch, которые не проверяют свойства исключения. Если исключение должно быть брошено, используйте параметр expected у аннотации @Test, если не должно быть, то тест и так будет провален, если оно таки будет брошено (и стек всё равно ведь, кажется, распечатают). try-catch полезны, если хочется проверить, что исключение брошено именно тогда, когда нужно или обладает правильными свойствами (в этом случае, кстати, имеет смысл подумать, не завести ли больше классов-исключений, чтобы их не приходилось по свойствам различать).

2017-03-11 15:20 UTC, yurii-litvinov commented on cli/src/test/java/CommandsTest.java
> +            assertTrue(true);
Вот это точно надо в отдельный тест с аннотацией @Test(expected = CommandException.class)

2017-03-11 15:23 UTC, KruchDmitriy commented on cli/src/main/java/commands/Command.java
> +    public Command(final String[] args) {}
Здесь я зафиксировал то, как можно создавать объекты класса Command.

2017-03-11 15:28 UTC, yurii-litvinov commented on cli/src/main/java/commands/Command.java
> +    public Command(final String[] args) {}
Всё равно в классе-потомке можно передать сюда null или пустой массив, так что это ни к чему не обязывает

2017-03-24 13:51 UTC, yurii-litvinov approved these changes
Теперь замечания совсем незначительные, так что зачтена.

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/commands/Command.java
> + * Abstract class that represents a command.
Это уже интерфейс, а не абстрактный класс :)

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/commands/CommandFactory.java
> +public final class CommandFactory {
Тут тоже по-хорошему надо комментарий

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/commands/Pwd.java
> +    public Pwd() {}
Кстати, а зачем он? Пустой public-конструктор без аргументов сгенерится и так, если ни одного конструктора не написать

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/core/exceptions/RunnerException.java
> +public class RunnerException extends Exception {
И тут неплохо бы комментарий

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +    }
По-хорошему это лучше на три теста разбить, чтобы если один не прошёл, можно было сразу локализовать проблему

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +        String[] args = {"ls", "-a", "src/test/resources/"};
~Под виндой не работает~

2017-03-24 13:51 UTC, yurii-litvinov commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +            assertTrue(true);
Мм, try-catch тут вообще лишний, а `assertTrue(true);` тем более

2017-04-03 20:57 UTC, merged