Grep implementation
KruchDmitriy/software-design pull request #2
Opened 2017-03-07 23:43 UTC by KruchDmitriy

2017-03-13 18:03 UTC, yurii-litvinov requested changes
Тут тоже тесты надо поправить, как и в CLI.

2017-03-13 18:03 UTC, yurii-litvinov commented on cli/src/main/java/commands/CommandFactory.java
> +                    return new Grep(args);
Неудобно, надо добавлять имя команды в два места. Наверняка кто-нибудь забудет. Лучше пытаться создать команду, потом попробовать присваивание, и уже если всё не получилось, вызывать как внешнюю. Но это можно не править, это скорее наблюдение.

2017-03-21 16:34 UTC, KruchDmitriy commented on cli/src/main/java/commands/CommandFactory.java
> +                    return new Grep(args);
Не понял, что Вы имеете в виду под словосочетанием "пытаться создать команду"? Я же не могу это сделать не зная заранее её имени.

2017-03-24 14:55 UTC, yurii-litvinov approved these changes
Исправления были сделаны с amend, force push или чем-то вроде? А то Вы вроде как поправили, а коммит всего один. В случае с гитом так лучше не делать, потому что репозиторий могли успеть склонить (я вот склонил, например), и у клонов история теперь не совпадает с основным репозиторием, что заставляет гит страдать.

В остальном всё ок, так что зачтена.

2017-04-03 21:04 UTC, merged