add ls, cd implementation
KruchDmitriy/software-design pull request #6
Opened 2017-04-19 00:29 UTC by YorovSobir

Думаю архитектуру лучшую чем то что есть придумать просто невозможно. Кроме класса CommandFactory остальные классы я даже не открывал, что говорит уже о хорошей архитектуре. Добавил два отдельных класса для соответствующих команд и тесты. Ничего исправлять не пришлось. 
Спасибо огромное автору!

2017-04-22 18:55 UTC, KruchDmitriy commented
:+1:  Даже разноцветное).

2017-05-09 20:01 UTC, yurii-litvinov requested changes
cd не уважает свои собственные действия, например, если сделать cd src и cd main, то получим `main: No such file or directory`. А вот cd src/main отработает нормально. Интересно, что ls без параметров знает про результаты cd, а ls с параметрами --- уже нет, и ругается так же как cd. Другие команды, типа pwd, тоже cd игнорируют. Поправьте это, пожалуйста.

А разноцветная выдача --- действительно прикольно

2017-05-09 20:01 UTC, yurii-litvinov commented on cli/src/main/java/ru/spbau/mit/commands/Cd.java
> +     * @param env environment that command executed with
Нельзя комментарии начинать сразу с `@param`, надо какой-то summary

2017-05-09 20:01 UTC, yurii-litvinov commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +        InputStream out;
А зачем так рано его объявлять? Лучше в месте первого использования, тут же всё равно эта переменная никому не нужна

2017-05-09 20:01 UTC, yurii-litvinov commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +
А тут две пустые строки, а принято одну. Да, я придираюсь :)

2017-05-09 20:01 UTC, yurii-litvinov commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +        String[] args2 = { "src/non_exist_dir" };
Под виндой не работает, слеши в другую сторону. Лучше использовать File.separatorChar

2017-05-30 17:59 UTC, YorovSobir commented on cli/src/main/java/ru/spbau/mit/commands/Cd.java
> +     * @param env environment that command executed with
Исправил

2017-05-30 17:59 UTC, YorovSobir commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +        InputStream out;
Исправил

2017-05-30 17:59 UTC, YorovSobir commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +
Исправил

2017-05-30 18:00 UTC, YorovSobir commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +        String[] args2 = { "src/non_exist_dir" };
Исправил, то что связано с cd и ls. Остальное пусть автор меняет:)

2017-05-30 18:00 UTC, YorovSobir commented
@yurii-litvinov

2017-05-30 18:18 UTC, KruchDmitriy commented on cli/src/test/java/ru/spbau/mit/CommandsTest.java
> +        String[] args2 = { "src/non_exist_dir" };
А тесты только для автора предназначены, а он под ubuntой сидит).

2017-06-03 14:32 UTC, KruchDmitriy commented
Задача вроде бы зачтена, поэтому мёржу.

2017-06-03 14:32 UTC, merged